# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
